Добавлен флаг, убирающий отображение числа в начале названия папки в содержании
irsural/sphinx-autotoc pull request #1
Opened 2024-01-29 09:07 UTC by UnicPlay

2024-01-30 04:57 UTC, Feelinglight requested changes

2024-01-30 04:57 UTC, Feelinglight commented on README.md
> +![sphinx_autotoc_get_headers_from_subfolder = False](https://imgur.com/xKokPBB.png)
Не должно быть ни одной ссылки на картинки на внешний сайт. Ни в какой нашей докуменатции. Где гарантии что через 10 лет эта ссылка не умрет?

2024-01-30 04:57 UTC, Feelinglight commented on README.md
> +#### ``sphinx_autotoc_trim_folder_numbers``
Написать зачем этот флаг нужен

2024-01-30 04:57 UTC, Feelinglight commented on README.md
> +У расширения есть три параметра, которые задаются переменными в **conf.py**.
числом

2024-01-30 04:57 UTC, Feelinglight commented on README.md
> +- ``False``
Пример генерации с False.

2024-01-30 04:57 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    trim = cfg["sphinx_autotoc_trim_folder_numbers"]
Что trim. Давай нормальные названия переменным

2024-01-30 04:57 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    match = re.match(r"^\d+\.\s(\S.*)", dir_path.name, re.DOTALL)
Зачем здесь регулярка?? Все что нужно попробовать скастить символы до первой точки к int и обработать ошибки. Элементарная операция.

2024-01-30 04:57 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    match = re.match(r"^\d+\.\s(\S.*)", path.name, re.DOTALL)
Почему нетривиальный шаблонный код повторяется в 2 местах? Сделай функцию. Здесь тоже не нужна регулярка

2024-01-30 07:27 UTC, UnicPlay commented on README.md
> +У расширения есть три параметра, которые задаются переменными в **conf.py**.
\+

2024-01-30 07:30 UTC, UnicPlay commented on README.md
> +- ``False``
Не понял, там чуть ниже лежат все примеры

2024-01-30 07:46 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    match = re.match(r"^\d+\.\s(\S.*)", path.name, re.DOTALL)
\+

2024-01-30 08:41 UTC, UnicPlay commented on README.md
> +![sphinx_autotoc_get_headers_from_subfolder = False](https://imgur.com/xKokPBB.png)
\+

2024-01-30 08:41 UTC, UnicPlay commented on README.md
> +#### ``sphinx_autotoc_trim_folder_numbers``
\+

2024-01-30 08:42 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    match = re.match(r"^\d+\.\s(\S.*)", dir_path.name, re.DOTALL)
Потому что мне казалось, что регулярка тоже элементарная операция
Исправил

2024-01-30 11:00 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    for i in range(len(path_name)):
Слишком сложно. Воспользуйся ``str.split('.')`` и ``str.lstrip(' ')``

2024-01-30 11:01 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    match = re.match(r"^\d+\.\s(\S.*)", dir_path.name, re.DOTALL)
Регулярка это совершенно нетривиальная операция. Особенно с таким шаблоном

2024-01-30 11:01 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    match = re.match(r"^\d+\.\s(\S.*)", dir_path.name, re.DOTALL)
Можешь закрыть conversation

2024-01-30 12:15 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    for i in range(len(path_name)):
\+

2024-01-30 12:16 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    header_style_is_irs_docs = cfg["sphinx_autotoc_get_headers_from_subfolder"]
\+

2024-01-31 03:22 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +            return ".".join(split_path[1:])
Сначала проверь длину, потом распакуй кортеж в 2 переменные и работай с ними.
Обращение по индексам непонятно.

2024-01-31 03:22 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +            split_path[1] = split_path[1].lstrip()
На такой строке будет работать неверно: 1..   name.rst

2024-01-31 03:22 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +            return ".".join(split_path[1:])
Используй maxsplit = 1

2024-01-31 10:05 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +            return ".".join(split_path[1:])
\+

2024-01-31 10:05 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +            return ".".join(split_path[1:])
\+

2024-01-31 10:05 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +            split_path[1] = split_path[1].lstrip()
\+

2024-02-01 05:44 UTC, Feelinglight requested changes

2024-02-01 05:44 UTC, Feelinglight commented on tests/test_make_indexes.py
> +    strlist = [
Переменная не нужна, пиши inline в декоратор

2024-02-01 05:44 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +            if number.isdigit() and name[0] == " ":
Почему имя обязано начинаться с пробела?

2024-02-01 05:44 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    1. Текст -> Текст
```suggestion
>>> trim_leading_numbers("1. Текст")
'Текст'
```
Не уверен нужны ли кавычки в 'Текст'. Нужно проверить пройдет ли тест

2024-02-01 05:44 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    Парсит файлы .rst в поисках автосаммари.
Отступы!

2024-02-01 05:44 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    1. Текст -> Текст
Отступы!

2024-02-01 05:44 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +                name = name.lstrip()
Сделай это перед проверкой на длину name

2024-02-01 08:42 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +            if number.isdigit() and name[0] == " ":
Я думал, что стандарт для называния файлов (и папок) - число, за ним точка, за ним пробел, за ним остальное название, на соответствие этому стандарту и делал проверку

2024-02-01 08:45 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    1. Текст -> Текст
Отступы сделал, про кавычки - не понял

2024-02-01 08:45 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    Парсит файлы .rst в поисках автосаммари.
\+

2024-02-01 08:49 UTC, UnicPlay commented on tests/test_make_indexes.py
> +    strlist = [
\+

2024-02-01 08:51 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +                name = name.lstrip()
Выше написал про стандарт

2024-02-01 09:07 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +                name = name.lstrip()
\+

2024-02-01 09:07 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +            if number.isdigit() and name[0] == " ":
\+

2024-02-01 09:20 UTC, Feelinglight approved these changes

2024-02-01 09:21 UTC, merged