Reformat paths
irsural/sphinx-autotoc pull request #2
Opened 2024-02-13 05:20 UTC by UnicPlay

2024-02-21 06:04 UTC, Feelinglight requested changes

2024-02-21 06:04 UTC, Feelinglight commented on tests/test_make_indexes.py
> +        cfg = activate_cfg(path)
Где эта функция объявлена?

2024-02-21 06:04 UTC, Feelinglight commented on tests/test_make_indexes.py
> +        path = Path(MAKE_INDEXES_TEST_PROJECTS_DIR) / "3_levels_of_nesting"
Вынеси общий для всех тестов код в функцию

2024-02-21 10:55 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +        main_page_dirs = {src: []}
\+

2024-02-21 10:55 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +
\+

2024-02-21 10:55 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    for root, docs in _iter_dirs(docs_directory, cfg):
\+

2024-02-21 10:56 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    src = docs_directory / "src"
\+

2024-02-25 04:56 UTC, UnicPlay commented on tests/test_make_indexes.py
> +            assert f.read() == """3 levels of nesting Test Project
Не сказал бы, что сильно лучше выглядит 
![image](https://github.com/irsural/sphinx-autotoc/assets/43138284/6f8bb2b0-162b-4f16-abe0-1177b512e396)

2024-02-25 04:57 UTC, UnicPlay commented on tests/test_make_indexes.py
> +        cfg = activate_cfg(path)
Почему-то уехала в отдельный коммит, который я не собирался отправлять, исправил

2024-02-25 04:57 UTC, UnicPlay commented on tests/test_make_indexes.py
> +        path = Path(MAKE_INDEXES_TEST_PROJECTS_DIR) / "3_levels_of_nesting"
\+

2024-02-25 04:58 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
>          os.remove(index_md)
\+

2024-02-25 06:56 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
>      index_md = (docs_directory / SPHINX_INDEX_FILE_NAME).with_suffix(".md")
Убрал совсем эту проверку, раньше она нужна была, чтоб собирать содержание не по файлу service.index.md, а по файлу service.index.rst.

2024-02-25 08:58 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    if "sphinx.ext.autosummary" in cfg.extensions and cfg.autosummary_generate:
\+

2024-02-25 08:59 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +            logger.info("No .rst file with recursive autosummary directive found, skipping...")
Исправил

2024-02-28 08:39 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +            _replace_autosummary_with_api_reference(autosummary_index, file_path, module_name)
\+

2024-03-01 06:00 UTC, Feelinglight commented on pyproject.toml
> +[tool.ruff]
Я же просил. В ОТДЕЛЬНОМ ПУЛ РЕКВЕСТЕ.
Мне сейчас отступы и прочую хрень которые тебе ruff изменил смотреть в diff???
Откатывай

2024-03-01 06:00 UTC, Feelinglight commented on tests/test_make_indexes.py
> +            assert f.read() == """3 levels of nesting Test Project
![image](https://github.com/irsural/sphinx-autotoc/assets/40621703/7f3d068d-2807-4700-a7b9-8de7492fc493)

2024-03-01 09:37 UTC, UnicPlay commented on pyproject.toml
> +[tool.ruff]
Откатил

2024-03-01 09:44 UTC, UnicPlay commented on tests/test_make_indexes.py
> +            assert f.read() == """3 levels of nesting Test Project
\+

2024-03-01 13:15 UTC, Feelinglight requested changes

2024-03-01 13:15 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    files = [Path(file) for file in glob.glob(f"{root}/**/[!_]*/*.rst", recursive=True)]
В этом расширении уже есть обход папок, нафига писать еще один. Ищи autosummary в первом обходе, когда составляются файлы содержания

2024-03-22 08:13 UTC, Feelinglight requested changes
Работает неправильно в первой же сборке irs_docs с дефолтными параметрами

2024-03-27 03:04 UTC, Feelinglight requested changes

2024-03-27 03:04 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +        return
Бросать ExtensionError, а не просто продолжать сборку без расширения

2024-03-28 04:51 UTC, Feelinglight approved these changes

2024-03-28 04:51 UTC, merged