Обновлён README.md
irsural/sphinx-autotoc pull request #3
Opened 2024-02-13 07:01 UTC by UnicPlay

2024-02-21 05:07 UTC, Feelinglight requested changes

2024-02-21 05:07 UTC, Feelinglight commented on README.md
> +Для того, чтобы папка не попала в содержание, её название должно начинаться с `_`
Зачем? Если для autosummary, то нужно игнорировать конкретно папку autosummary

2024-02-21 05:07 UTC, Feelinglight commented on README.md
> +   module
Что такое module?

2024-02-21 05:07 UTC, Feelinglight commented on README.md
> +### sphinx.ext.autosummary
Этот раздел проверен на чистом проекте? Подозреваю так как у тебя написано работать не будет

2024-02-21 05:07 UTC, Feelinglight commented on README.md
> +`docs/src/folder/publicapi.rst`
Что за publicapi, это не public api. Назови autosummary.rst, если это возможно

2024-02-21 05:07 UTC, Feelinglight commented on README.md
> +как "API reference".
Это должно быть кастомным именем

2024-02-21 05:07 UTC, Feelinglight commented on README.md
> +В противном случае, ссылка будет отображаться как "publicapi" и вести себя неправильно.
В противном чему случае?

2024-02-21 09:59 UTC, UnicPlay commented on README.md
> +## Совместимость с другими расширениями
\+

2024-02-21 10:01 UTC, UnicPlay commented on README.md
> +Для того, чтобы папка не попала в содержание, её название должно начинаться с `_`
Не только для autosummary, ещё для всяких files, images, templates, styles и так далее

2024-02-21 10:07 UTC, UnicPlay commented on README.md
> +В противном случае, ссылка будет отображаться как "publicapi" и вести себя неправильно.
Если НЕ выполнено хотя бы одно из двух условий:
1. Импортирован и включен autosummary (в `conf.py`)
2. создан rst-документ в котором есть директивы autosummary и recursive и есть название документируемого модуля module

2024-02-21 10:12 UTC, UnicPlay commented on README.md
> +как "API reference".
\+

2024-02-21 10:43 UTC, UnicPlay commented on README.md
> +### sphinx.ext.autosummary
Проверен на uvdic

2024-02-22 03:59 UTC, Feelinglight commented on README.md
> +### sphinx.ext.autosummary
Проверить на чистом проекте. Это расширение делается не только для uvdic

2024-02-22 03:59 UTC, Feelinglight commented on README.md
> +   module
Я это и так знаю. Откуда это должен знать читатель документации?

2024-02-22 04:00 UTC, Feelinglight commented on README.md
> +Для того, чтобы папка не попала в содержание, её название должно начинаться с `_`
Там не должно быть rst файлов

2024-02-22 04:03 UTC, Feelinglight commented on README.md
> +`docs/src/folder/publicapi.rst`
Не надо парсить все rst файлы. Там может быть 1000+ страниц по 1000+ строк. Построчно все будешь проверять?

Сделай название файла фиксированным, без conf.py. Пусть будет **autotoc.autosummary.rst**

2024-02-22 04:08 UTC, Feelinglight commented on README.md
> +Задаёт текст ссылки на autosummary. По умолчанию - **API reference**.
А если у меня 10 таких файлов? Все будут API reference? Нужно задавать через rst файл с директивой autosummary

2024-02-22 04:08 UTC, Feelinglight commented on README.md
> +В противном случае, ссылка будет отображаться как "publicapi" и вести себя неправильно.
Не надо мне писать это сюда. Переформулируй readme, чтобы это стало понятно там. Читатель документации все пул реквесты должен просмотреть чтобы разобраться?

2024-02-22 04:08 UTC, UnicPlay commented on README.md
> +   module
Если пользователю нужен рабочий autosummary - он уже скорее всего настроил autosummary
Если не нужен - он пропустит этот раздел совсем

2024-02-22 06:35 UTC, Feelinglight commented on README.md
> +   module
Ничего это не значит. Пользователю нужно воспользоваться твоим расширением и он может вообще не знать ни про какие autosummary. В этом readme должна быть рабочая инструкция на твое расширение. 

Я не говорю что нужно переписывать сюда документацию autosummary. Здесь должна быть тупая инструкция как заставить твое расширение работать. Пользователю знание как работает autosummary для этого вообще не нужно. 

Про настройки conf.py ты написал, про файл написал, а содержимое файла внезапно читай иди где-нибудь в другом месте.

2024-02-28 07:04 UTC, UnicPlay commented on README.md
> +`docs/src/folder/publicapi.rst`
\+

2024-02-28 07:13 UTC, UnicPlay commented on README.md
> +   module
Эту часть переделал

2024-02-28 07:13 UTC, UnicPlay commented on README.md
> +В противном случае, ссылка будет отображаться как "publicapi" и вести себя неправильно.
\+

2024-02-28 08:40 UTC, UnicPlay commented on README.md
> +Задаёт текст ссылки на autosummary. По умолчанию - **API reference**.
\+

2024-02-28 08:41 UTC, UnicPlay commented on README.md
> +### sphinx.ext.autosummary
Проверил на чистом, работает

2024-02-28 08:44 UTC, UnicPlay commented on README.md
> +Для того, чтобы папка не попала в содержание, её название должно начинаться с `_`
Зато заносятся _autosummary и _templates, в них ведь есть rst файлы

Разве не лучше явно показать, что у нас заносится в содержание, а что - нет?

2024-03-01 05:25 UTC, Feelinglight commented on README.md
> +### sphinx.ext.autosummary
Как он модуль для autosummary находит?

2024-03-01 05:31 UTC, Feelinglight commented on README.md
> +Для того, чтобы папка не попала в содержание, её название должно начинаться с `_`
Спорно, _autosummary всегда называется _autosummary, его можно найти по имени и нет проблем явно указать что папка _autosummary игнорируется. А _templates вообще не должны лежать в src. Они лежат выше.

Нижнее подчеркивание это не такой редкий символ (вообще не редкий) и он легко может стоять в начале папки с rst файлами. Придется разбираться потом почему в содержании не появилась папка. Может будет и не сложно, но лучше этого избежать

2024-03-01 05:57 UTC, Feelinglight requested changes

2024-03-01 05:57 UTC, Feelinglight commented on README.md
> +5. Первая строка файла с директивами - заголовок ссылки для этого файла
Вот тут не понял. В примере ниже этого нет вроде

2024-03-01 05:57 UTC, Feelinglight commented on README.md
> +6. В файле с директивами указан документируемый модуль, класс или функция.
Это не полная информация, sphinx не найден модуль без дополнительных танцев, он должен резолвиться через path

2024-03-01 05:57 UTC, Feelinglight commented on README.md
> +`module` - название документируемого модуля.
python-модуля

2024-03-01 08:12 UTC, UnicPlay commented on README.md
> +### sphinx.ext.autosummary
Модуль, который autosummary документирует, должен быть "доступен" для autosummary
"Доступен" - значит, что он либо добавлен в Path с помощью `sys.path.insert` в `conf.py`, либо установлен в том окружении (виртуальном, глобальном), из которого запускается Sphinx
Когда тестил - пробовал оба варианта, оба сработали
Это нужно написать в README?

2024-03-01 09:11 UTC, UnicPlay commented on README.md
> +5. Первая строка файла с директивами - заголовок ссылки для этого файла
Забыл пример дополнить, исправил

2024-03-01 09:19 UTC, UnicPlay commented on README.md
> +`module` - название документируемого модуля.
\+

2024-03-01 09:19 UTC, UnicPlay commented on README.md
> +6. В файле с директивами указан документируемый модуль, класс или функция.
\+

2024-03-01 12:58 UTC, Feelinglight commented on README.md
> +### sphinx.ext.autosummary
Конечно

2024-03-01 13:02 UTC, Feelinglight requested changes

2024-03-01 13:02 UTC, Feelinglight commented on README.md
> +==============
Это должно быть заголовком rst или просто первая строка нужна? Эта строчка потом не вылезет нигде в сгенерированном сайте (кроме содержания)?

2024-03-02 06:48 UTC, UnicPlay commented on README.md
> +### sphinx.ext.autosummary
\+

2024-03-02 09:16 UTC, UnicPlay commented on README.md
> +==============
Просто первой строкой, в сайте не вылезает нигде

2024-03-12 03:44 UTC, merged