Добавлен natsort, после сортировки папки появляются раньше файлов
irsural/sphinx-autotoc pull request #4
Opened 2024-03-26 08:58 UTC by UnicPlay

2024-04-01 09:06 UTC, Feelinglight requested changes

2024-04-01 09:06 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +from natsort import natsorted
Это не стандартный модуль. Почему зависимости не обновлены?

2024-04-01 09:06 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    is_directory = not file_name.startswith("autotoc.")  # "not" потому что в сортировке false появляется раньше true
Комментарий пишем над строкой, а не внутри

2024-04-01 09:06 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    is_directory = not file_name.startswith("autotoc.")  # "not" потому что в сортировке false появляется раньше true
Сделай явную проверку на то, что путь - это папка, а не startswith какой то там префикс

2024-04-04 08:11 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    is_directory = not file_name.startswith("autotoc.")  # "not" потому что в сортировке false появляется раньше true
Это ты убрал чтобы в отдельном пулл реквесте сделать?

2024-04-04 08:16 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    is_directory = not file_name.startswith("autotoc.")  # "not" потому что в сортировке false появляется раньше true
И вообще почему опять под 2 задачи пулл реквест???

2024-04-04 08:20 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    is_directory = not file_name.startswith("autotoc.")  # "not" потому что в сортировке false появляется раньше true
> Нельзя просто добавлять в отдельные списки добавлять папки и файлы и их сортировать? Так понятнее будет и надежнее

Либо передавать везде не просто список файлов, а список кортежей, либо dataclass-ов вида

```python
@dataclass
class SrcPath:
    path: Path
    is_dir: bool
```

2024-04-04 08:27 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    is_directory = not file_name.startswith("autotoc.")  # "not" потому что в сортировке false появляется раньше true
Понял, в search_paths есть только файлы. Тогда проще всего отдельные списки

2024-04-12 11:09 UTC, Feelinglight requested changes

2024-04-12 11:09 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    is_generated_by_extension = not file_name.startswith(f"{SPHINX_SERVICE_FILE_PREFIX}.")
Еще раз. Мы **не** проверяем, что папка является файлов по префиксу autotoc. Передаем в эту функцию **явно** кто файл, а кто папка

2024-04-15 06:30 UTC, Feelinglight requested changes

2024-04-15 06:30 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    file_paths = set()
Обнови документацию к функции

2024-04-15 06:30 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +            if p.name.startswith(f"{SPHINX_SERVICE_FILE_PREFIX}."):
Это ты в другую функцию просто перенес проверку по префиксу? Так не пойдет

2024-04-15 06:31 UTC, Feelinglight requested changes

2024-04-15 06:31 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    skeys = natsorted(mp.keys())
Напиши тесты на то что папки должны быть выше файлов

2024-04-16 06:04 UTC, Feelinglight requested changes

2024-04-16 06:04 UTC, Feelinglight commented on tests/test_make_indexes.py
> +class TestMakeSearchPaths:
1 тест на всю функцию? Серьезно?

Покрой полностью тестами. **Используй parametrize**.

И напиши фикстуру которая будет создавать деревья файлов.

2024-04-16 06:26 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
>      :param index: Добавлять ли в путь к файлу корневую папку.
Как тогда в функции определять, ссылки создаются для индексного файла (autotoc.rst) или для файла папки(autotoc.folder.rst)? Между ними есть принципиальная разница: индексный файл находится в корне, и ко всем ссылкам в нём требуется в начале добавлять "src", чтоб они работали.

2024-04-17 08:55 UTC, Feelinglight requested changes

2024-04-17 08:55 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +            if p.stem.split(".", maxsplit=1) == [SPHINX_SERVICE_FILE_PREFIX, root.name]:
?

2024-04-17 08:55 UTC, Feelinglight commented on tests/test_make_indexes.py
> +def file_tree(tmp_path):
Аналогично autotoc

2024-04-17 08:55 UTC, Feelinglight commented on tests/test_make_indexes.py
> +    def test_make_search_paths(self, root_addition, files, index, expected_file_paths, file_tree):
Такого теста быть не должно. Называй тесты по тестируемой функциональности функции. ``test_folders_before_files`` названа правильно

2024-04-19 04:12 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
>      :param index: Добавлять ли в путь к файлу корневую папку.
Для того, чтоб убрать индекс отсюда, нужно переделать ещё раз _list_files, так что это сделаю после того, как #5 пройдёт и в этой ветке произойдёт rebase

2024-04-19 07:20 UTC, Feelinglight requested changes
Попытаться исправить index

2024-05-02 10:12 UTC, Feelinglight requested changes

2024-05-02 10:12 UTC, Feelinglight commented on tests/test_make_indexes.py
> +            0 if Path(item).name.startswith("autotoc") else 1 for item in search_paths
А нельзя просто перечислить что должно получиться?

2024-05-02 10:12 UTC, Feelinglight commented on tests/test_make_indexes.py
> +    def test_search_paths_generation(
Тесты не годятся. Не нужно проверять всю функцию одним тестом. Нужно проверять разные пути выполнения одной функции. Примеры:

- У всех папок добавлен префикс autotoc
- Папки раньше файлов в списке
- Файл содержания текущей папки не добавляется
- и т. д.

Это все должны быть разные тесты, возможно, с parametrize, если это удобно

2024-05-20 06:39 UTC, Feelinglight requested changes

2024-05-20 06:39 UTC, Feelinglight commented on tests/test_make_indexes.py
> +@pytest.fixture(scope='session')
Фикстуры должны быть в conftest

2024-05-20 06:39 UTC, Feelinglight commented on tests/test_make_indexes.py
> +    yield _make_search_paths(root, file_list + folder_list)
Тестируемые функции в фикстурах вызывать нельзя

2024-05-20 06:39 UTC, Feelinglight commented on tests/test_make_indexes.py
> +        assert Path("file1.rst") in search_paths_list
Зачем в этом тесте папки в ``search_paths_list``?

2024-05-20 06:39 UTC, Feelinglight commented on tests/test_make_indexes.py
> +        assert Path("folder2/autotoc.folder2.rst") in search_paths_list
Зачем в этом тесте файлы в ``search_paths_list``?

2024-05-20 06:39 UTC, Feelinglight commented on tests/test_make_indexes.py
> +        assert Path("autotoc.src.rst") not in search_paths_list
Зачем в этом тесте файлы в ``search_paths_list``?

2024-05-20 06:39 UTC, Feelinglight commented on tests/test_make_indexes.py
>  import pytest
Тесты на natsort вообще есть здесь???

2024-05-21 09:56 UTC, Feelinglight commented on tests/test_make_indexes.py
> +    yield _make_search_paths(root, file_list + folder_list)
В других функциях тоже не нужно.
Вызывай в тестах

2024-05-21 09:58 UTC, Feelinglight requested changes
Исправить оставшиеся замечания

2024-05-22 04:31 UTC, Feelinglight approved these changes

2024-05-22 04:31 UTC, Feelinglight commented
@UnicPlay Влей мастер в эту ветку и реши конфликты

2024-05-22 07:54 UTC, merged