Теперь расширение не обходит папки без rst-файлов
irsural/sphinx-autotoc pull request #5
Opened 2024-04-04 06:28 UTC by UnicPlay

2024-04-04 08:38 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +        dirs[:] = [d for d in dirs if not any(part in ignore_list for part in (relative_root / d).parts)]
Че то это не так работает как раньше по-моему.

2024-04-04 08:38 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +        dirs[:] = [d for d in dirs if not any(part in ignore_list for part in (relative_root / d).parts)]
Зачем здесь бесполезные ``[:]``?

2024-04-04 08:46 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    ignore_list = IGNORE_LIST.union({'_'})  # Add underscore prefix to ignore list
Убирай IGNORE_LIST вообще. Брать игноры из конфига sphinx, из ``exclude_patterns``. 

Для сопоставления используй [Matcher](https://github.com/sphinx-doc/sphinx/blob/cb8a28dd7e11a7a0a5bc9694163fc164433e2f36/sphinx/util/matching.py#L74)

Весь остальной хлам не должен добавляться и так, потому что там rst нет

2024-04-11 06:48 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    ignore_list = IGNORE_LIST.union({'_'})  # Add underscore prefix to ignore list
Не сделано

2024-04-11 07:02 UTC, Feelinglight requested changes

2024-04-11 07:02 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> -                or any(part.startswith("_") for part in p.parts))
Папка _autosummary будет исключаться автоматически?

2024-04-11 07:02 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    matcher = Matcher(IGNORE_LIST)
Напиши unit тесты на функцию ``_list_files``

2024-04-11 09:00 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> -                or any(part.startswith("_") for part in p.parts))
Да, т.к. она начинается с _

2024-04-11 10:04 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    ignore_list = IGNORE_LIST.union({'_'})  # Add underscore prefix to ignore list
IGNORE_LIST оставлен, чтоб не тащить exclude_patterns конфига "вглубь" по функциям до самого _list_files

он теперь инициализируется пустым, а в ходе работы [дополняется](https://github.com/irsural/sphinx-autotoc/pull/5/files#diff-58b5b77771e60b082ae431a98a81256154fc77f245af95d07380a8acc3648eadR64) контентом из exclude_patterns

2024-04-11 10:32 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> -                or any(part.startswith("_") for part in p.parts))
Нет, исправил: игнорируются все файлы и папки, начинающиеся с _

2024-04-12 10:36 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    ignore_list = IGNORE_LIST.union({'_'})  # Add underscore prefix to ignore list
Нет, так делать не надо. В общем случае глобальные изменяемые переменные это зло и их следует избегать. 

Тащить аргументы по функциям это нормально. И вообще у тебя в _flatmap и так есть Config, возьми там и передай в _list_dirs.

Тесты на исключения добавь.

2024-04-12 10:37 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> -                or any(part.startswith("_") for part in p.parts))
Плохо исправил, вставляй фильтр в _list_dirs, в тот же if, где проверяешь расширение файла на .rst

2024-04-12 11:06 UTC, Feelinglight requested changes

2024-04-12 11:06 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    IGNORE_LIST.add("**/_*")
Мы вроде только папки исключаем. Это не будет файлы трогать?

2024-04-12 15:18 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    ignore_list = IGNORE_LIST.union({'_'})  # Add underscore prefix to ignore list
Какие исключения ты имеешь в виду? Питоновские, вроде FileNotFoundError, или какие-то другие?

2024-04-12 15:19 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    IGNORE_LIST.add("**/_*")
Теперь не будет

2024-04-17 07:04 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +def _list_files(docs_directory: Path, patterns: list[str]) -> set[Path]:
Не patterns это, называй переменные нормально

2024-04-17 07:04 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
>      Составляет список файлов в папках. Игнорирует файлы и папки, указанные в IGNORE_LIST
Паша, сколько можно. Че за IGNORE_LIST. Исправляй сопутствующие переменные, документацию и тесты, хватит по ложечке каждый комментарий исправлять

2024-04-17 07:04 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    IGNORE_LIST.add("**/_*")
Тест на это написан?

2024-04-17 07:06 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    IGNORE_LIST.add("**/_*")
Тест на это написан?

2024-04-17 07:12 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    IGNORE_LIST.add("**/_*")
> Не понял почему

Потому что теперь этой строки нет, проверка проводится по-другому

2024-04-17 07:12 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +    for file in _list_files(docs_directory, cfg["exclude_patterns"]):
Нет, он ругается на другой способ доступа (`cfg.exclude_patterns`)

2024-04-17 07:12 UTC, Feelinglight commented on tests/test_make_indexes.py
> +    def test_non_rst_files_ignored(self, mock_docs_dir):
Это вообще говоря не так должно быть.

Нужно ориентироваться на переменную сфинкса в конфиге. Добавь на это задачу, в этом пулл реквесте не надо исправлять

2024-04-17 07:12 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    ignore_list = IGNORE_LIST.union({'_'})  # Add underscore prefix to ignore list
Которые передаются в функцию **аргументами**

2024-04-17 07:24 UTC, Feelinglight requested changes

2024-04-17 07:24 UTC, Feelinglight commented on tests/test_make_indexes.py
> +            Path("."),
map, либо set comprehension

2024-04-17 07:24 UTC, Feelinglight commented on tests/test_make_indexes.py
> +class TestListFiles:
Не вижу теста на флаг ``dir_has_rst_files``

2024-04-17 07:24 UTC, Feelinglight commented on tests/test_make_indexes.py
> +    docs_dir = tmp_path / "docs"
Убирай эту портянку и делай parametrize для каждого теста отдельно. Эти тесты очень сложно читать, потому что каждый из них зачем-то создает папки и файлы которые нужны только для других тестов

2024-04-17 07:24 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    IGNORE_LIST.add("**/_*")
> > Не понял почему
> 
> Потому что теперь этой строки нет, проверка проводится по-другому

На вопросы отвечать только после запроса изменений

2024-04-17 07:24 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    for file in _list_files(docs_directory, cfg["exclude_patterns"]):
Что значит другой способ. В mypy не должно быть ни одного варнинга. Сделай отдельным пулл реквестом экшен, который будет запускать тесты mypy и ruff

2024-04-17 07:24 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    for file in _list_files(docs_directory, cfg["exclude_patterns"]):
Потом влей его в эту ветку

2024-04-17 07:38 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    for file in _list_files(docs_directory, cfg["exclude_patterns"]):
> Потом влей его в эту ветку

Хотя вливать лучше не надо

2024-05-02 10:30 UTC, Feelinglight requested changes

2024-05-02 10:30 UTC, Feelinglight commented on tests/test_make_indexes.py
> +    def test_list_files(self, dir_structure: list[Path], expected_paths: set[Path], tmp_path: Path,
Аналогично пулл реквесту с natsort. Использование parametrize не обязывает делать один единственный тест на все случаи жизни.

Тесты должны проверять конкретные пути выполнения функции.

2024-05-02 10:30 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +                    and file_path.suffix == '.rst'\
rst недостаточно, нужно передавать сюда из конфигурации сфинкса [включенные расширения](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-source_suffix)

2024-05-02 10:30 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +            if not any(matcher.match(file_path_part) for file_path_part in file_path.parts) \
Разве это так должно работать, не нужно ли матчить только полный путь?

2024-05-02 10:31 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +                    and file_path.suffix == '.rst'\
Сделать в отдельном пулл реквесте, после принятия этого

2024-05-02 10:32 UTC, Feelinglight commented on tests/test_make_indexes.py
> +            Path("."),
???

2024-05-02 10:34 UTC, Feelinglight commented on tests/test_make_indexes.py
> +    docs_dir = tmp_path / "docs"
Лучше не стало

2024-05-02 10:50 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +            if not any(matcher.match(file_path_part) for file_path_part in file_path.parts) \
Если указать паттерн, допустим, "**/files/**" (то есть игнорировать всё в папке files, где бы она ни была), и матчить "folder/files/file.txt', то матчер выдаст False, и файл покажется. Если матчить по частям - такой паттерн отрабатывает как ожидалось (то есть игнорит любые файлы с названием files, игнорит файлы на любой степени вложенности в папку files).

2024-05-03 05:47 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +            if not any(matcher.match(file_path_part) for file_path_part in file_path.parts) \
https://github.com/sphinx-doc/sphinx/blob/c41aab829d667a6fb5c9e6e8daf2d4b47b7ddebe/sphinx/util/matching.py#L101

2024-05-17 09:20 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +            if not any(matcher.match(file_path_part) for file_path_part in file_path.parts) \
Можно ли использовать https://github.com/sphinx-doc/sphinx/blob/c41aab829d667a6fb5c9e6e8daf2d4b47b7ddebe/sphinx/util/matching.py#L113 вместо всей list_files?

2024-05-20 09:56 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +            if not any(matcher.match(file_path_part) for file_path_part in file_path.parts) \
Как ты наличие rst в папках проверишь если всю функцию заменишь?

2024-05-20 09:58 UTC, Feelinglight requested changes

2024-05-20 09:58 UTC, Feelinglight commented on tests/test_make_indexes.py
> +    def test_list_files(self, dir_structure: list[Path], expected_paths: set[Path], tmp_path: Path,
До сих пор один тест на все случаи жизни

2024-05-20 09:59 UTC, Feelinglight commented
Ты вообще сделал хоть один коммит после запроса изменений?

2024-05-22 04:59 UTC, Feelinglight requested changes

2024-05-22 04:59 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +                and not relative_root.name.startswith('_')
Вынеси в переменные. Что за if на 3 строки

2024-05-22 04:59 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +        if any(patfilter([root], pattern) for pattern in exclude_patterns):
patfilter принимает строку, зачем в него список пихать?
Ниже аналогично

2024-05-22 04:59 UTC, Feelinglight commented on tests/test_make_indexes.py
> +    def test_list_files_exclude_patterns_files(self, tmp_path: Path) -> None:
Мало тестов на exclude. Сделай больше с parametrize

2024-05-22 04:59 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +                not any(patfilter([str(file_path)], pattern) for pattern in exclude_patterns)
Ты убедился что patfilter работает так же как Matcher? Это необходимо, потому что sphinx обрабатывает exclude_patterns через Matcher

2024-05-22 06:32 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +                not any(patfilter([str(file_path)], pattern) for pattern in exclude_patterns)
Нашёл вариант, в котором Matcher нормально матчит, сейчас верну Matcher.
А так да, "под капотом" они так и так используют re.match, только выход разный

2024-05-23 04:39 UTC, Feelinglight requested changes

2024-05-23 04:39 UTC, Feelinglight commented on tests/test_make_indexes.py
> +                # в корневой папке
https://docs.pytest.org/en/latest/example/parametrize.html#different-options-for-test-ids
``pytest.param( ... , id=)``

2024-05-23 04:39 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +            if any([matcher(str(file_path)), file_path.suffix != '.rst', relative_root.name.startswith('_')]):
Переделай на ``or``, это понятнее читается. 

И вообще это вроде не влазит в 100 символов. Разбей на переменные и проверяй их в if-е

2024-05-24 03:53 UTC, Feelinglight approved these changes

2024-05-24 03:54 UTC, Feelinglight commented
@UnicPlay Влей master в эту ветку

2024-05-24 07:16 UTC, merged