Добавлен экшен для автоматического запуска проверок mypy и ruff
irsural/sphinx-autotoc pull request #6
Opened 2024-04-19 07:39 UTC by UnicPlay

2024-05-22 04:35 UTC, Feelinglight requested changes

2024-05-22 04:35 UTC, Feelinglight commented on .github/workflows/ruff_mypy_check.yaml
> +        run: ruff check
Список команд, которые нужно запускать возьми здесь: https://okr.irsural.ru/git/okr/irbk_core/src/branch/master/.gitea/workflows/run_tests.yaml

Makefile тоже добавь

2024-06-03 04:28 UTC, Feelinglight requested changes

2024-06-03 04:28 UTC, Feelinglight commented on Makefile
> +analyze: prepare
Не надо делать зависимости на установку

2024-06-03 04:28 UTC, Feelinglight commented on Makefile
> +	python3 -m pip install pytest
Не надо делать установку в запуске тестов

2024-06-03 04:28 UTC, Feelinglight commented on Makefile
> +	python3 -m pip install mypy
Установка должна выполняться 1 раз из requirements

2024-06-03 04:28 UTC, Feelinglight commented on pyproject.toml
> +ignore_missing_imports = "True"
Зачем?

2024-06-03 04:28 UTC, Feelinglight commented on Makefile
> +linter: prepare
lint

2024-06-03 04:28 UTC, Feelinglight commented on Makefile
> +	python3 -m ruff format sphinx_autotoc tests/*.py --check
Перенести в lint

2024-06-03 04:28 UTC, Feelinglight commented on .github/workflows/ruff_mypy_check.yaml
> +name: Ruff and Mypy checks
Добавь кэширование

2024-06-03 04:28 UTC, Feelinglight commented on Makefile
> +	sudo apt-get install -y python3-pip
Для установки python есть специальный экшен

2024-06-03 09:15 UTC, UnicPlay commented on pyproject.toml
> +ignore_missing_imports = "True"
Потому что mypy в strict-режиме ругался на импорты очень многих библиотек, вроде pytest, os, natsort. Видимо, это какой-то локальный косяк, потому что в экшенах таких ошибок нет. Убрал.

2024-06-04 07:29 UTC, Feelinglight commented on Makefile
> +analyze: prepare
Это не значит, что надо убрать цель для установки

2024-06-04 07:31 UTC, Feelinglight commented on pyproject.toml
> +ignore_missing_imports = "True"
Ставь комментарии с type ignore на конкретные ошибки

2024-06-04 07:33 UTC, Feelinglight requested changes

2024-06-04 07:33 UTC, Feelinglight commented on pyproject.toml
> +    'alabaster==0.7.13',
Это тебе реально столько зависимостей надо?

2024-06-04 11:28 UTC, Feelinglight approved these changes

2024-06-04 11:28 UTC, merged