Добавлена обработка суффиксов source_suffix
irsural/sphinx-autotoc pull request #7
Opened 2024-06-06 11:49 UTC by UnicPlay

2024-06-06 12:02 UTC, Feelinglight requested changes

2024-06-06 12:02 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +    docs_directory: Path, exclude_patterns: list[str], source_suffixes: list[str] | dict[str, str]
Делай тайп хинты из typing. Это все должно будет работать на python 3.7.
В pyproject и в экшенах тоже поменяй версию python.
Отельным пулл реквестом.

2024-06-06 12:59 UTC, UnicPlay commented on sphinx_autotoc/__init__.py
> +        source_suffixes = source_suffixes.keys()  # type: ignore[assignment]
Чтоб привести source_suffix к единой конструкции, он может быть как словарём, так и списком.
Игнор mypy - потому что ругается на то, что я переопределяю тип переменной (был dict | list, стал просто list)

2024-06-18 07:48 UTC, Feelinglight commented on sphinx_autotoc/__init__.py
> +        source_suffixes = source_suffixes.keys()  # type: ignore[assignment]
``in`` работает для списков и словарей. Зачем приводить все к списку

2024-06-18 07:50 UTC, Feelinglight requested changes
Исправить последнее замечание

2024-06-18 11:26 UTC, Feelinglight approved these changes

2024-06-18 11:26 UTC, merged